print('-' * 35)
print("Tugas 1 SISOP Kelas-A")
print('-' * 35)
print("Nama : Radya Ardi Ninang Pudyastuti")
print("NPM  : 21083010097")
print('-' * 35)
print("notes:")
print('-' * 35)
print("Halo Dunia!")
print("Ini adalah skrip Bash pertamaku di Linux")

